### ISSUE TITLE
Extract CSS

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper-template-rollup#1]
Newer versions of Rollup make it possible to emit virtual dependencies. It *should* therefore be possible to bake out the CSS associated with each chunk, and lazily load it (though for most apps having a single blob of CSS for the entire app is probably acceptable too), as is possible with webpack.

I've never done it, so not yet sure how to go about it. I bet @tivac has some ideas though 😀

**Comment by tivac** [comment]
The code to do it for `modular-css` is a little gnarly since I have to care about the rollup dependency graph as well as a shadow `modular-css` dependency graph that rollup doesn't really care about, but you can see the code that does all the work here:

https://github.com/tivac/modular-css/blob/ef7cb96adcb34d4fc2b635aa43b3554341ee0502/packages/rollup/rollup.js#L135-L233

I apologize for the complexity, if an annotated run-through of all that code and what it's doing would be helpful lemme know.

https://github.com/tivac/modular-css/blob/ef7cb96adcb34d4fc2b635aa43b3554341ee0502/packages/rollup/rollup.js#L136-L166

Is probably the most useful non-`modular-css` specific code, since that's ripping through the bundles and returned by rollup and seeing what CSS files should go w/ each entry point.

**Comment by Rich-Harris** [comment]
Thank you! Will study this and let you know if I have questions

**Comment by tivac** [comment]
And for actually emitting the assets you want [`this.emitAsset()`](https://github.com/rollup/rollup/wiki/Plugins#thisemitasset-assetname-source-), or [`this.setAssetSource`](https://github.com/rollup/rollup/wiki/Plugins#thissetassetsource-assetid-source-) if you don't know the contents right away. `modular-css` uses both!

**Comment by Rich-Harris** [comment]
Closing as this is handled by Sapper itself (as long as `emitCss: true` is set) in https://github.com/sveltejs/sapper/pull/406
